# Generated by Django 2.0.6 on 2018-06-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packages',
            new_name='Package',
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('order',)},
        ),
    ]
